language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0

before_script:
  - sudo apt-get install php-codesniffer
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  #- phpcs src
after_script:
  - php vendor/bin/coveralls -v
